### ISSUE TITLE
Beeper

### ISSUE THREAD

**Issue by suderman** [sumnerevans/home-manager-config#2]
Thank you for sharing the beeper package you have here. FYI, when the new version was released yesterday, I had to change the package name from "beeper-beta" to "beeper".

https://github.com/suderman/nixos/blob/main/overlays/pkgs/beeper.nix

**Comment by sumnerevans** [comment]
You're welcome!

I work at Beeper, so I'm running our internal beta builds, that's why the URL looks different and I use the `beeper-beta` package name.

**Comment by suderman** [comment]
Haha, I only noticed that after I wrote this. Great project. :-)
